set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports y]
set_property PACKAGE_PIN T16 [get_ports a]
set_property PACKAGE_PIN W13 [get_ports b]
set_property PACKAGE_PIN M14 [get_ports y]
