set_property -dict {PACKAGE_PIN T16 IOSTANDARD LVCMOS33} [get_ports in_sws[3]]
set_property -dict {PACKAGE_PIN W13 IOSTANDARD LVCMOS33} [get_ports in_sws[2]]
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS33} [get_ports in_sws[1]]
set_property -dict {PACKAGE_PIN G15 IOSTANDARD LVCMOS33} [get_ports in_sws[0]]

set_property -dict {PACKAGE_PIN V8 IOSTANDARD LVCMOS33} [get_ports seg_data[6]] 
set_property -dict {PACKAGE_PIN W8 IOSTANDARD LVCMOS33} [get_ports seg_data[5]]
set_property -dict {PACKAGE_PIN U7 IOSTANDARD LVCMOS33} [get_ports seg_data[4]]
set_property -dict {PACKAGE_PIN V7 IOSTANDARD LVCMOS33} [get_ports seg_data[3]]
set_property -dict {PACKAGE_PIN Y7 IOSTANDARD LVCMOS33} [get_ports seg_data[2]]
set_property -dict {PACKAGE_PIN Y6 IOSTANDARD LVCMOS33} [get_ports seg_data[1]]
set_property -dict {PACKAGE_PIN V6 IOSTANDARD LVCMOS33} [get_ports seg_data[0]]