set_property -dict {PACKAGE_PIN W13 IOSTANDARD LVCMOS33} [get_ports a[0]]
set_property -dict {PACKAGE_PIN T16 IOSTANDARD LVCMOS33} [get_ports a[1]]
set_property -dict {PACKAGE_PIN M14 IOSTANDARD LVCMOS33} [get_ports y[0]]
set_property -dict {PACKAGE_PIN M15 IOSTANDARD LVCMOS33} [get_ports y[1]]
set_property -dict {PACKAGE_PIN G14 IOSTANDARD LVCMOS33} [get_ports y[2]]
set_property -dict {PACKAGE_PIN D18 IOSTANDARD LVCMOS33} [get_ports y[3]]